In [1]:
import os 
os.chdir("..")
from perlib.forecaster import *

In [2]:
import pandas as pd
data = pd.read_csv("./perlib/datasets/winequality-white.csv",delimiter=";")

In [3]:
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.00,0.27,0.36,20.70,0.04,45.00,170.00,1.00,3.00,0.45,8.80,6
1,6.30,0.30,0.34,1.60,0.05,14.00,132.00,0.99,3.30,0.49,9.50,6
2,8.10,0.28,0.40,6.90,0.05,30.00,97.00,1.00,3.26,0.44,10.10,6
3,7.20,0.23,0.32,8.50,0.06,47.00,186.00,1.00,3.19,0.40,9.90,6
4,7.20,0.23,0.32,8.50,0.06,47.00,186.00,1.00,3.19,0.40,9.90,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.20,0.21,0.29,1.60,0.04,24.00,92.00,0.99,3.27,0.50,11.20,6
4894,6.60,0.32,0.36,8.00,0.05,57.00,168.00,0.99,3.15,0.46,9.60,5
4895,6.50,0.24,0.19,1.20,0.04,30.00,111.00,0.99,2.99,0.46,9.40,6
4896,5.50,0.29,0.30,1.10,0.02,20.00,110.00,0.99,3.34,0.38,12.80,7
4897,6.00,0.21,0.38,0.80,0.02,22.00,98.00,0.99,3.26,0.32,11.80,6

In [4]:
#If the "auto" parameter is True, train and test operations are performed according to the best result among the "Regressor" or "Classifier" models. To use models manually, enter the "auto" parameter as False.
m_info.testsize = .2
m_info.y        = "fixed acidity"
m_info.modelname= "SVR"
m_info.auto  = False

In [5]:
from perlib.core.models.mmodels import models
m = models(m_info)

In [6]:
from perlib.core.train import mTrain
train = mTrain(dataFrame=data,object=m)

In [7]:
preds, evaluate = train.predict(metric=["mape","mae"])

In [8]:
preds

     Predicts  Actual
0        7.21    7.40
1        6.22    5.90
2        6.46    6.90
3        6.50    6.50
4        6.98    7.50
..        ...     ...
975      6.19    6.40
976      7.02    7.60
977      8.62    8.60
978      6.60    6.30
979      6.40    6.50

[980 rows x 2 columns]

In [9]:
evaluate

{'mean_absolute_percentage_error': 6.02665884490294,
 'mean_absolute_error': 0.40952540188072045}

In [10]:
# If you want to make any other data predictions you can use the train.tester
# func after train.predict. You can make predictions with
predicts = train.tester(path="./models/Data-SVR-2024-03-08-14-41-40.pkl", testData=data.iloc[:,1:][-20:])

In [11]:
predicts

    Predicts
0       6.47
1       6.38
2       6.38
3       6.04
4       6.28
5       5.56
6       6.39
7       6.39
8       6.44
9       6.73
10      7.20
11      6.04
12      6.62
13      6.20
14      6.53
15      6.38
16      6.42
17      7.19
18      5.81
19      6.61